PMS\Bundle\ProjectBundle\Entity\Project:
    type: entity
    table: project
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        blurb:
            type: string
            nullable: true
        description:
            type: string
            nullable: true
        devUrl:
            type: string
            nullable: true
        prodUrl:
            type: string
            nullable: true
        image:
            type: string
            nullable: true
        createdBy:
            type: string
            gedmo:
                blameable:
                    on: create
        updatedBy:
            type: string
            gedmo:
                blameable:
                    on: update
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    fields:
                        - name
    manyToOne:
        Type:
            targetEntity: \PMS\Bundle\ProjectBundle\Entity\Type
            inversedBy: projects
            joinColumn: type_id
            referencedColumnName: id
        Category:
            targetEntity: \PMS\Bundle\ProjectBundle\Entity\Category
            inversedBy: projects
            joinColumn: category_id
            referencedColumnName: id
        Status:
            targetEntity: \PMS\Bundle\ProjectBundle\Entity\Status
            inversedBy: projects
            joinColumn: status_id
            referencedColumnName: id
        Client:
            targetEntity: \PMS\Bundle\UserBundle\Entity\Client
            inversedBy: projects
            joinColumn: client_id
            referencedColumnName: id
    oneToMany:
        Developers:
            targetEntity: \PMS\Bundle\UserBundle\Entity\Developer
            mappedBy: project
    indexes:
        search_idx:
            columns: slug
    properties:
        name:
            - Length:
                min: 1
                max: 250
        blurb:
            - Length:
                    min: 1
                    max: 50
        devUrl:
                - Url: ~
        prodUrl:
                - Url: ~
        image:
                - Image: ~