PMS\Bundle\ProjectBundle\Entity\Type:
    type: entity
    table: project_type
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        description:
            type: string
            nullable: true
        createdBy:
            type: string
            gedmo:
                blameable:
                    on: create
        updatedBy:
            type: string
            gedmo:
                blameable:
                    on: update
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    fields:
                        - name
    manyToOne:
        Parent:
            targetEntity: \PMS\Bundle\ProjectBundle\Entity\Type
            inversedBy: projects
            joinColumn: parent_id
            referencedColumnName: id
    oneToMany:
        Projects:
            targetEntity: \PMS\Bundle\ProjectBundle\Entity\Project
            mappedBy: type
        Children:
            targetEntity: \PMS\Bundle\ProjectBundle\Entity\Type
            mappedBy: type
    indexes:
        search_idx:
            columns: slug
    properties:
        name:
            - Length:
                min: 1
                max: 250