parameters:
#    pms_project.example.class: PMS\Bundle\ProjectBundle\Example

services:
#    pms_project.example:
#        class: %pms_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
